#define DESKFLOW_NO_ENTRYPOINT
#include "../src/app.cpp"
#include <iostream>
static void pump(unsigned ms){auto end=GetTickCount64()+ms;do{MSG m{};while(PeekMessageW(&m,nullptr,0,0,PM_REMOVE)){if(m.message!=WM_QUIT){TranslateMessage(&m);DispatchMessageW(&m);}}Sleep(5);}while(GetTickCount64()<end);}
static void saveWindow(HWND window,const std::filesystem::path& file){UpdateWindow(window);DwmFlush();RECT r{};GetWindowRect(window,&r);auto bitmap=captureRegion(r);if(!bitmap||!saveBitmapPng(bitmap,file))throw std::runtime_error("Documentation screenshot export failed");DeleteObject(bitmap);}
static LRESULT CALLBACK sampleWindow(HWND window,UINT message,WPARAM wp,LPARAM lp){if(message==WM_PAINT){PAINTSTRUCT ps{};auto dc=BeginPaint(window,&ps);RECT r{};GetClientRect(window,&r);FillRect(dc,&r,(HBRUSH)GetStockObject(WHITE_BRUSH));auto font=CreateFontW(-32,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI");auto old=SelectObject(dc,font);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(32,42,56));RECT colour{640,60,810,130};auto blue=CreateSolidBrush(RGB(164,213,255));FillRect(dc,&colour,blue);DeleteObject(blue);TextOutW(dc,40,40,L"Find files instantly.",21);TextOutW(dc,40,105,L"Keep your clipboard history.",28);TextOutW(dc,40,170,L"Capture, recognize and translate.",32);SelectObject(dc,old);DeleteObject(font);EndPaint(window,&ps);return 0;}return DefWindowProcW(window,message,wp,lp);}
int wmain(int argc,wchar_t** argv){if(argc!=2&&(argc!=3||std::wstring(argv[2])!=L"--files-only"))return 2;auto output=std::filesystem::absolute(argv[1]);std::filesystem::create_directories(output);auto original=GetThreadDesktop(GetCurrentThreadId());auto desktop=CreateDesktopW(L"DeskFlowDocumentation",nullptr,nullptr,0,GENERIC_ALL,nullptr);if(!desktop||!SetThreadDesktop(desktop))return 3;SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);OleInitialize(nullptr);INITCOMMONCONTROLSEX common{sizeof(common),ICC_WIN95_CLASSES};InitCommonControlsEx(&common);int result=1;
    try{if(!SwitchDesktop(desktop))throw std::runtime_error("Cannot switch synthetic documentation desktop");
        Application app(GetModuleHandleW(nullptr),output/L"synthetic-data"/(L"run-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64())),true,60000);WNDCLASSW cls{};cls.lpfnWndProc=Application::procedure;cls.hInstance=app.instance;cls.lpszClassName=L"DeskFlowDocumentationHost";cls.style=CS_DBLCLKS;cls.hIcon=LoadIconW(app.instance,MAKEINTRESOURCEW(101));RegisterClassW(&cls);
        auto host=CreateWindowExW(0,cls.lpszClassName,L"DeskFlow",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,70,70,1050,650,nullptr,nullptr,app.instance,&app);SetWindowPos(host,HWND_TOP,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_SHOWWINDOW);KillTimer(host,9);KillTimer(host,2);app.pendingQuery=false;app.listInFlight=false;
        const wchar_t* names[]{L"Annual report 2026.pdf",L"Budget.xlsx",L"Design notes.md",L"DeskFlow guide.txt",L"Meeting notes.txt",L"Project assets",L"Roadmap.md",L"Screenshot.png",L"Travel plan.txt",L"Weekly summary.docx"};
        app.indexStatus.total=48126;app.indexStatus.complete=true;app.indexStatus.stage=L"ready";
        for(int i=0;i<10;++i)app.fileRows.push_back({i+1,names[i],L"C:\\Demo\\Projects\\"+std::wstring(names[i]),i==5,(uint64_t)(1024*(i+1)),i!=5,134358480000000000ULL+(uint64_t)i*600000000});app.select(0);app.invalidate();pump(80);saveWindow(host,output/L"files.png");
        if(argc>2&&std::wstring(argv[2])==L"--files-only"){app.quit();SwitchDesktop(original);std::cout<<"Synthetic file preview saved\n";ExitProcess(0);}
        for(auto value:{L"Todo: prepare the release notes.",L"会议记录：整理示例项目，检查文档截图。",L"https://example.com/demo",L"Example clipboard text — stored locally."}){ClipPayload payload;payload.source=L"Example App";ClipFormat format;format.format=CF_UNICODETEXT;format.data.resize((wcslen(value)+1)*2);memcpy(format.data.data(),value,format.data.size());payload.formats.push_back(std::move(format));app.history->append(payload);}
        app.mode=1;app.layout();app.query(true);pump(150);saveWindow(host,output/L"clipboard.png");app.select(0);app.showHistoryPreview();pump(100);saveWindow(app.floatingPreview.window(),output/L"clipboard-preview.png");app.hide();
        WNDCLASSW seedClass{};seedClass.lpfnWndProc=sampleWindow;seedClass.hInstance=app.instance;seedClass.lpszClassName=L"DeskFlowDocumentationSample";RegisterClassW(&seedClass);auto seed=CreateWindowExW(WS_EX_TOPMOST,seedClass.lpszClassName,L"Demo",WS_POPUP,130,120,850,300,nullptr,nullptr,app.instance,nullptr);SetWindowPos(seed,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_SHOWWINDOW);UpdateWindow(seed);DwmFlush();
        OcrResult ocr;ocr.width=770;ocr.height=230;ocr.lines={{L"Find files instantly.",10,8,500,50},{L"Keep your clipboard history.",10,73,620,50},{L"Capture, recognize and translate.",10,138,740,50}};
        beginCapture(host,{}, {},[ocr](HBITMAP source,std::atomic_bool&){return renderTranslation(source,ocr,{L"快速找到文件。",L"保留你的剪贴板历史。",L"截图、识别与原图翻译。"});});auto overlay=FindWindowW(L"DeskEfficiencyCaptureOverlay",nullptr);
        POINT hoverPixel{815,200};ScreenToClient(overlay,&hoverPixel);SendMessageW(overlay,WM_MOUSEMOVE,0,MAKELPARAM(hoverPixel.x,hoverPixel.y));pump(80);SendMessageW(overlay,WM_MOUSEMOVE,0,MAKELPARAM(hoverPixel.x,hoverPixel.y));UpdateWindow(overlay);DwmFlush();auto hoverView=captureRegion({100,80,1140,520});saveBitmapPng(hoverView,output/L"capture-hover.png");DeleteObject(hoverView);
        SendMessageW(overlay,WM_LBUTTONDOWN,MK_LBUTTON,MAKELPARAM(160,150));SendMessageW(overlay,WM_MOUSEMOVE,MK_LBUTTON,MAKELPARAM(930,380));SendMessageW(overlay,WM_LBUTTONUP,0,MAKELPARAM(930,380));pump(80);
        RECT view{100,100,1140,500};auto bitmap=captureRegion(view);saveBitmapPng(bitmap,output/L"capture.png");DeleteObject(bitmap);SendMessageW(overlay,WM_KEYDOWN,'T',0);pump(150);bitmap=captureRegion(view);saveBitmapPng(bitmap,output/L"translation.png");DeleteObject(bitmap);
        SendMessageW(overlay,WM_KEYDOWN,'P',0);pump(80);auto pin=FindWindowW(L"DeskEfficiencyPinnedImage",nullptr);saveWindow(pin,output/L"pin.png");SendMessageW(pin,WM_CLOSE,0,0);
        auto scrolling=beginScrollingCapture(host,{160,150,930,380},{});pump(150);if(scrolling){SetWindowDisplayAffinity(scrolling,WDA_NONE);saveWindow(scrolling,output/L"scrolling.png");SendMessageW(scrolling,WM_CLOSE,0,0);}
        auto original=captureRegion({160,150,930,380});ShowWindow(seed,SW_HIDE);app.acceptCapturedImage(original,L"image");app.cancelTranslation=false;auto recognised=new Result;recognised->type=7;recognised->generation=app.captureGeneration;recognised->text=L"Find files instantly.\r\nKeep your clipboard history.\r\nCapture, recognize and translate.";app.receive(recognised);SetWindowTextW(app.resultEdit,app.detailText.c_str());pump(100);saveWindow(host,output/L"ocr.png");app.hide();
        ShowWindow(seed,SW_SHOWNOACTIVATE);RECT region{};GetWindowRect(seed,&region);recording_detail::beginWithDestination(seed,region,RecordingFormat::Mp4,output/L"synthetic-recording.mp4");pump(2300);auto recorder=FindWindowW(L"DeskFlowRecordingController",nullptr);SetWindowDisplayAffinity(recorder,WDA_NONE);auto edges=recording_detail::status().borders;for(auto edge:edges)SetWindowDisplayAffinity(edge,WDA_NONE);SetWindowPos(recorder,HWND_TOPMOST,region.left,region.bottom+16,0,0,SWP_NOSIZE|SWP_NOACTIVATE);pump(80);RECT controls{};GetWindowRect(recorder,&controls);RECT demo{region.left-12,region.top-12,region.right+12,controls.bottom+12};auto recordingView=captureRegion(demo);saveBitmapPng(recordingView,output/L"recording.png");DeleteObject(recordingView);for(auto edge:edges)SetWindowDisplayAffinity(edge,WDA_EXCLUDEFROMCAPTURE);SetWindowDisplayAffinity(recorder,WDA_EXCLUDEFROMCAPTURE);shutdownRecording();
        app.quit();DestroyWindow(seed);result=0;
    }catch(const std::exception& e){std::cerr<<e.what()<<'\n';shutdownImageTools();shutdownRecording();}
    SwitchDesktop(original);std::cout<<"Documentation preview result "<<result<<'\n';std::cout.flush();ExitProcess(result);
}
